# Generated by Django 5.0.7 on 2024-08-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_newsfilms_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfilms',
            name='img_url',
            field=models.CharField(max_length=1000),
        ),
    ]
